# Generated by Django 2.2.1 on 2019-06-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='has_car',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ida',
            field=models.CharField(default='Ida', max_length=50),
        ),
    ]
