# Generated by Django 2.2.1 on 2019-05-23 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
