# Generated by Django 2.2.1 on 2019-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190612_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='manejo',
            field=models.BooleanField(default=False),
        ),
    ]
