# Generated by Django 2.2.1 on 2019-05-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190523_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(default='camino punta de aguilas 4307', max_length=200),
        ),
    ]
