# Generated by Django 2.2.1 on 2019-05-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ubicacion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(default='Campus San Joaquín, Pontificia Universidad Católica de Chile', max_length=200),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
