# Generated by Django 2.2.1 on 2019-05-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190524_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='conductor',
            field=models.BooleanField(default=False),
        ),
    ]
