# Generated by Django 2.2.1 on 2019-05-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190524_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='capacity',
            new_name='capacidad',
        ),
    ]
