# Generated by Django 2.2.1 on 2019-05-25 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190524_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Auto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
