# Generated by Django 2.2.1 on 2019-05-25 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pasajeros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajeros',
            name='user',
        ),
        migrations.AddField(
            model_name='pasajeros',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
