# Generated by Django 2.2.1 on 2019-05-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190524_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tengo_ida',
            field=models.BooleanField(default=False),
        ),
    ]
