# Generated by Django 2.2.1 on 2019-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_tengo_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_conductor',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
