# Generated by Django 2.2.1 on 2019-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_id_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('has_car', models.BooleanField(default=False)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
